# prompt_store.py
from core.config import AI_MODEL_QUALITY
"""
Manages AI prompts in a local SQLite database (prompts.db).

How it works:
  - Two prompts are GENERIC (same for every user):
      intake_questions   - generates interview questions from any resume
      intake_xml_builder - builds XML from any Q&A answers
    These are seeded from static text the first time they are needed.

  - Two prompts are PERSONAL (specific to each user):
      relevance_check  - describes THIS person's specialization and what to skip
      resume_tailor    - describes THIS person's background for honest tailoring
    These are GENERATED by Claude reading the user's real profile.
    They are never hardcoded. They are created once and stored.

Users never need to open this file, the database, or edit anything.
Everything is automatic.
"""

import os
import json
import sqlite3
from datetime import datetime

def _db_path(path=None): return _db_file(path)

def _db_file() -> str:
    """Resolve prompts.db path — exe-aware."""
    import sys as _sys
    if getattr(_sys, "frozen", False):
        base = os.path.dirname(_sys.executable)
    else:
        import sys as _sys3
        base = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        if not os.path.isdir(os.path.join(base, "api")):
            base = os.path.dirname(os.path.abspath(_sys3.executable))
    data_dir = os.path.join(base, "data")
    os.makedirs(data_dir, exist_ok=True)
    return os.path.join(data_dir, "prompts.db")

DB_FILE = _db_file()

# Prompt name constants -- used by all code files
PROMPT_RELEVANCE_CHECK    = "relevance_check"
PROMPT_RESUME_TAILOR      = "resume_tailor"
PROMPT_INTAKE_QUESTIONS   = "intake_questions"
PROMPT_INTAKE_XML         = "intake_xml_builder"
PROMPT_INTAKE_XML_DIRECT  = "intake_xml_direct"   # use-as-is path — no Q&A
PROMPT_EXPERIENCE_ENHANCE   = "experience_enhance"
PROMPT_JOB_EXPERIENCE_PRIORITY = "job_experience_priority"

# Which prompts are personal (generated per user) vs generic (static)
PERSONAL_PROMPTS = {PROMPT_RELEVANCE_CHECK, PROMPT_RESUME_TAILOR}
GENERIC_PROMPTS  = {
    PROMPT_INTAKE_QUESTIONS,
    PROMPT_INTAKE_XML,
    PROMPT_EXPERIENCE_ENHANCE,
    PROMPT_JOB_EXPERIENCE_PRIORITY,
}


# -- Database helpers ---------------------------------------------
def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn


def _ensure_table() -> None:
    """Create the prompts table if it does not exist."""
    conn = _connect()
    try:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS prompts (
                name        TEXT PRIMARY KEY,
                content     TEXT NOT NULL DEFAULT '',
                description TEXT NOT NULL DEFAULT '',
                created_at  TEXT,
                updated_at  TEXT
            )
        """)
        conn.commit()
    finally:
        conn.close()


# -- Public API ---------------------------------------------------
def get_prompt(name: str) -> str:
    """
    Returns the prompt content for the given name.
    Raises a clear error if the prompt does not exist yet.
    """
    _ensure_table()
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT content FROM prompts WHERE name = ?", (name,)
        ).fetchone()
    finally:
        conn.close()

    if row:
        return row["content"]

    if name in PERSONAL_PROMPTS:
        raise ValueError(
            f"[SETUP REQUIRED] Personal prompt '{name}' is missing from prompts.db. "
            f"Run:  python migrate_prompts.py  (existing users) "
            f"OR  python resume_intake.py  (new users)"
        )
    else:
        raise ValueError(
            f"[SETUP REQUIRED] Prompt '{name}' is missing from prompts.db. "
            f"Run:  python migrate_prompts.py"
        )



def delete_prompt(name: str) -> None:
    """Delete a prompt from the DB so it regenerates on next run."""
    try:
        db = _db_file()
        con = sqlite3.connect(db)
        con.execute("DELETE FROM prompts WHERE name = ?", (name,))
        con.commit()
        con.close()
    except Exception:
        pass

def get_profile_hash(profile: dict) -> str:
    """Stable hash of the profile used to generate personal prompts."""
    import hashlib, json as _j
    key_fields = {
        "name":             profile.get("name", ""),
        "years_experience": profile.get("years_experience", 0),
        "summary":          profile.get("summary", "")[:200],
        "skills":           profile.get("skills", {}),
        "experience":       [
            {"title": j.get("title",""), "company": j.get("company","")}
            for j in profile.get("experience", [])[:4]
        ],
    }
    raw = _j.dumps(key_fields, sort_keys=True)
    return hashlib.sha256(raw.encode()).hexdigest()[:16]


def store_profile_hash(h: str) -> None:
    """Store the profile hash used to generate personal prompts."""
    set_prompt("_profile_hash", h, "Hash of profile when personal prompts were last generated.")


def get_stored_profile_hash() -> str:
    """Return the stored profile hash, or empty string if never set."""
    try:
        return get_prompt("_profile_hash") or ""
    except (ValueError, Exception):
        return ""


def personal_prompts_match_profile(profile: dict) -> bool:
    """True if personal prompts were generated from the current profile."""
    try:
        if not profile:
            return True
        stored = get_stored_profile_hash()
        if not stored:
            return False
        return stored == get_profile_hash(profile)
    except Exception:
        return True   # any error — don't force regenerate


def set_prompt(name: str, content: str, description: str = "") -> None:
    """Inserts or updates a prompt. Safe to call multiple times."""
    _ensure_table()
    now  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    conn = _connect()
    try:
        conn.execute("""
            INSERT INTO prompts (name, content, description, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(name) DO UPDATE SET
                content     = excluded.content,
                description = excluded.description,
                updated_at  = excluded.updated_at
        """, (name, content, description, now, now))
        conn.commit()
    finally:
        conn.close()


def prompt_exists(name: str) -> bool:
    """Returns True if this prompt is already in the database."""
    _ensure_table()
    conn = _connect()
    try:
        row = conn.execute(
            "SELECT 1 FROM prompts WHERE name = ?", (name,)
        ).fetchone()
        return row is not None
    finally:
        conn.close()


def list_prompts() -> list:
    """Returns all prompts with name, description, updated_at."""
    _ensure_table()
    conn = _connect()
    try:
        rows = conn.execute(
            "SELECT name, description, updated_at FROM prompts ORDER BY name"
        ).fetchall()
        return [dict(r) for r in rows]
    finally:
        conn.close()


def all_prompts_ready() -> bool:
    """Returns True if all required prompts exist in the database."""
    required = [
        PROMPT_RELEVANCE_CHECK,
        PROMPT_RESUME_TAILOR,
        PROMPT_INTAKE_QUESTIONS,
        PROMPT_INTAKE_XML,
        PROMPT_EXPERIENCE_ENHANCE,
        PROMPT_JOB_EXPERIENCE_PRIORITY,
    ]
    return all(prompt_exists(n) for n in required)


# -- Generic prompt content (same for every user) -----------------
_GENERIC_INTAKE_QUESTIONS = """You are a resume intake assistant. Your job is to read a resume and
generate a targeted set of questions to fill in missing, unclear, or
incomplete information so a complete, accurate base resume data file
can be built.

You must return ONLY a valid JSON array. No preamble, no explanation,
no markdown code fences. Just the raw JSON array.

Each item in the array is an object with exactly three fields:
  "id"       -> integer, starting from 1
  "question" -> the question to ask the user, in plain simple English
  "why"      -> one short sentence explaining why this matters

WHAT TO ASK ABOUT:
- Contact details that are missing (email, phone, LinkedIn, GitHub)
- Each job: exact start/end dates if unclear, the team or project name
  and what it actually was (product? internal tool? client system?),
  daily/weekly scale of the work (records processed, users, requests),
  the specific problem they solved and what changed after they fixed it,
  technologies actually used hands-on
- Each project: what real problem it solved, who used it, any measurable
  outcome (time saved, accuracy, scale)
- Education: university name if missing, graduation year, degree name
- Skills: any tools or languages used regularly that aren't listed

WHAT NOT TO ASK:
- Do NOT ask about target job roles or what kind of jobs they want —
  the base resume covers their full background, role targeting happens
  at application time
- Do NOT ask about work authorization, visa status, or location
  preferences — these are not part of a resume profile
- Do NOT ask about salary expectations or availability
- Do NOT ask anything already clearly answered in the resume

IMPORTANT — TEAM vs PROJECT vs APPLICATION:
- When a resume mentions a name like "CKYC" or "CRM", ask whether it
  was a team name, an application they built, a client system they
  maintained, or something else — do not assume it is an application

METRIC QUESTIONS — be specific and direct:
- Instead of "tell me more about your work", ask
  "How many records did the system process per day/month?"
- Instead of "what was the outcome", ask
  "How long did it take to diagnose the issue, and what was the
  business impact while it was broken?"
- If there is a number in the resume (60K images, 50K training images,
  86.5% accuracy), confirm it is correct and ask for context around it

DEPTH OVER BREADTH:
- Detailed resumes need fewer questions (6-10)
- Thin resumes need more (up to 15)
- Prioritise questions that will produce the strongest resume bullets —
  a question about a specific problem solved and its outcome is worth
  more than five questions about dates and tools

Return ONLY the JSON array:
[
  {"id": 1, "question": "...", "why": "..."}
]"""


_GENERIC_INTAKE_XML = """You are a resume data builder. Your job is to create a
complete, accurate resume_data.xml from a resume and a conversation transcript.

Return ONLY valid XML starting with <?xml version="1.0" encoding="UTF-8"?>
No preamble, no explanation, no markdown fences. Raw XML only.

━━━ STRUCTURE ━━━

<?xml version="1.0" encoding="UTF-8"?>
<profile>
    <meta>
        <years_experience>NUMBER</years_experience>
        <work_authorization>CPT / OPT / H1B / Green Card / Citizen</work_authorization>
        <experience_highlight>true</experience_highlight>
    </meta>
    <personal>
        <name></name>
        <email></email>
        <phone></phone>
        <location></location>
        <linkedin></linkedin>
        <github></github>
    </personal>
    <summary>2-4 sentences. See SUMMARY RULES below.</summary>
    <skills>
        <category name="languages"><skill>C#</skill>...</category>
        <category name="frameworks"><skill>.NET</skill>...</category>
        <category name="machine_learning"><skill>TensorFlow</skill>...</category>
        <category name="tools_platforms"><skill>Azure DevOps</skill>...</category>
        <category name="databases"><skill>SQL Server</skill>...</category>
        <category name="practices"><skill>Agile</skill>...</category>
    </skills>
    <experience>
        <job>
            <title></title>
            <company></company>
            <location></location>
            <duration></duration>
            <bullets>
                <bullet>Strong achievement bullet. See BULLET RULES below.</bullet>
            </bullets>
        </job>
    </experience>
    <education>
        <degree>
            <name></name>
            <school></school>
            <year>YYYY or YYYY - Present or YYYY - YYYY</year>
        </degree>
    </education>
    <projects>
        <project>
            <name></name>
            <tech>comma-separated technologies</tech>
            <bullets>
                <bullet>What was built, what problem it solved, measurable outcome.</bullet>
            </bullets>
        </project>
    </projects>
    <volunteer>
        <activity>
            <role></role>
            <organization></organization>
            <description></description>
        </activity>
    </volunteer>
</profile>

━━━ SUMMARY RULES ━━━
- 2-4 direct, specific sentences about their actual experience
- NEVER use: "Expert in", "proven expertise", "passionate", "results-driven",
  "dynamic", "leverage", "synergy", or any similar resume buzzwords
- Mention their actual domain (e.g. banking, ML, .NET) and real scale/impact
- Sound like a person wrote it, not a job posting

━━━ BULLET RULES ━━━
- Start with a strong past-tense verb (Built, Led, Resolved, Optimized, Delivered)
- Include actual numbers and names where known from the conversation
- Use the REAL name of products/teams — if they said it was called "TrackWizz CKYC"
  use that, not a generic "data validation application"
- If they clarified a team name vs an app name, reflect that correctly
- 5-8 bullets per job for senior roles, 3-5 for internships
- Each bullet is one complete sentence, max 2 printed lines

━━━ SKILLS RULES ━━━
- Only include skills actually mentioned in the resume or conversation
- If Angular/AngularJS was mentioned, include it under frameworks
- If SQL Server was mentioned, include it under databases
- Use separate categories: languages, frameworks, machine_learning (if applicable),
  tools_platforms, databases, practices
- Omit empty categories

━━━ GENERAL RULES ━━━
- Use ONLY information from the resume or conversation — never invent
- Use [PLACEHOLDER] only for genuinely unknown values like GitHub URL
- Include ALL jobs and ALL projects mentioned — do not drop any
- Return ONLY the XML, nothing else
- For education <year>: use the EXACT year the user stated in the conversation,
  not a date inferred from the resume header or document metadata. If they said
  "2025 to present" write "2025 - Present". Never guess or infer the start year."""


_GENERIC_INTAKE_XML_DIRECT = """You are a resume data builder. Your job is to create a
complete, accurate resume_data.xml directly from a resume PDF text.
There is no Q&A conversation — extract everything from the resume text alone.

Return ONLY valid XML starting with <?xml version="1.0" encoding="UTF-8"?>
No preamble, no explanation, no markdown fences. Raw XML only.

Extract and infer as much as possible from the resume text:
- Personal info: name, email, phone, location, LinkedIn, GitHub
- Work experience: all jobs with titles, companies, dates, bullet points
- Education: degrees, schools, graduation years
- Skills: categorise into languages, frameworks, tools, databases, practices
- Projects: names, tech stacks, descriptions
- Volunteer: roles and organisations

━━━ RULES ━━━
- Use ONLY information present in the resume text — never invent
- Use [PLACEHOLDER] for genuinely missing values like GitHub if not shown
- Keep all bullet points as written — do not paraphrase or summarise
- Include ALL jobs and ALL projects — do not drop any
- For education <year>: use the exact year shown in the resume
- Return ONLY the XML, nothing else

━━━ STRUCTURE ━━━
<?xml version="1.0" encoding="UTF-8"?>
<profile>
    <meta>
        <years_experience>NUMBER</years_experience>
        <work_authorization>CPT / OPT / H1B / Green Card / Citizen</work_authorization>
        <experience_highlight>true</experience_highlight>
    </meta>
    <personal>
        <name></name><email></email><phone></phone>
        <location></location><linkedin></linkedin><github></github>
    </personal>
    <summary>2-3 direct sentences about their actual background and domain.</summary>
    <skills>
        <category name="languages"><skill>C#</skill>...</category>
        <category name="frameworks"><skill>.NET</skill>...</category>
        <category name="tools_platforms"><skill>Azure DevOps</skill>...</category>
        <category name="practices"><skill>Agile</skill>...</category>
    </skills>
    <experience>
        <job>
            <title></title><company></company>
            <location></location><duration></duration>
            <bullets><bullet>Exact bullet from resume.</bullet></bullets>
        </job>
    </experience>
    <education>
        <degree><name></name><school></school><year></year></degree>
    </education>
    <projects>
        <project>
            <name></name><tech></tech>
            <bullets><bullet>What was built and what it does.</bullet></bullets>
        </project>
    </projects>
    <volunteer>
        <activity><role></role><organization></organization><description></description></activity>
    </volunteer>
</profile>"""


_GENERIC_EXPERIENCE_ENHANCE = """You are a resume writer. Your job is to rewrite work experience
bullets so they are cleaner, clearer, and more achievement-focused --
using ONLY what the user has actually told you. Nothing else.

You will receive:
  - A job role (title, company, dates)
  - The existing bullets for that role
  - Enhancement Q&A: answers the user gave about numbers and outcomes

========================================================
ABSOLUTE HONESTY RULES -- never break these:
========================================================

1. USE ONLY WHAT IS GIVEN.
   Every fact, number, technology, and outcome in your rewrite must
   come DIRECTLY from either the existing bullets or the Q&A answers.
   Do not infer, estimate, or assume anything.

2. NO INVENTED NUMBERS.
   If the user gave you a number (e.g. "10,000 records"), use it.
   If they did not give a number, do not write one -- not even
   "significantly", "substantially", or vague phrases like
   "large scale". Just describe what happened without a quantity.

3. [no additional info] MEANS NOTHING NEW.
   If a Q&A answer is "[no additional info]", treat that question
   as if it was never asked. Do not use it as a prompt to invent.

4. DO NOT UPGRADE VAGUE ANSWERS.
   If the user said "I fixed some bugs", write "Fixed production
   bugs" -- not "Reduced bug rate by 30%" or "Improved system
   stability". Use their exact level of detail, just expressed
   with a strong verb.

5. TECHNOLOGIES IN BULLETS MUST ALREADY EXIST.
   Only mention a tool or library if it appears in the existing
   bullets or was explicitly named in a Q&A answer.

========================================================
STYLE RULES -- apply after the honesty rules:
========================================================

- Start every bullet with a strong past-tense action verb
  (Led, Built, Diagnosed, Reduced, Automated, Delivered, Engineered,
  Resolved, Designed, Implemented, Streamlined, Authored).
- If a number or outcome exists in the source, lead with it early
  (first 7 words where possible).
- Maximum 2 printed lines per bullet. Cut every unnecessary word.
- 4 to 6 bullets per role. Consolidate if there are more.
- Do NOT mention the company name inside bullets -- it is in the header.

CORRECT example (number came from user's answer):
  "Eliminated a recurring pipeline timeout affecting 10,000+ records
   by rewriting validation as a chunked batch script."

CORRECT example (no number given -- do not invent one):
  "Resolved a recurring pipeline timeout by rewriting validation
   as a chunked batch script."

WRONG -- number not from the user:
  "Improved system throughput by 40% using batch scripting."

Return ONLY a JSON array of strings. No preamble, no markdown:
["Bullet one.", "Bullet two.", ...]"""


_GENERIC_JOB_EXPERIENCE_PRIORITY = """You are a resume strategist helping a candidate maximise their
chance of selection for a specific job.

You will receive:
  - A job description
  - The candidate's full experience and projects with bullets
  - The candidate's skills list

Your task: REORDER bullets within each job to put the most
relevant ones first for this specific JD. Return ALL content —
never drop any job, never drop any project, never remove bullets.

========================================================
RULES — READ CAREFULLY:
========================================================

1. REORDER ONLY — DO NOT DROP ANYTHING.
   - Return EVERY job in the experience list. Do not drop any job.
   - Return EVERY project. Do not drop any project.
   - Return ALL bullets for each job — just reorder them so the
     most relevant bullet for this JD appears first.
   - The candidate spent real effort writing every bullet. Removing
     any of them is not allowed.

2. YOU MAY ADD ONE EXTRA BULLET PER JOB (use sparingly).
   Only add if the underlying work is clearly implied by existing
   bullets and skills. Every word in a new bullet must already
   appear somewhere in the candidate's profile. No invented skills,
   no invented numbers, no invented technologies.

3. NEVER INVENT NEW CAPABILITIES.
   You may NOT mention any technology, framework, tool, or domain
   that does not already appear in the candidate's skills or bullets.

4. PROJECT ORDER.
   Reorder projects — most relevant to this JD first — but return
   ALL of them with ALL their bullets intact.

5. BULLET TEXT.
   Do not rewrite, shorten, or paraphrase existing bullets.
   Return the exact text of each bullet as given to you.

Relevance signals to look for in the JD:
  - Required technologies, languages, and frameworks
  - Domain keywords (banking, ML, APIs, cloud, data pipelines)
  - Job duties that map directly to the candidate's real work

Return ONLY valid JSON — no markdown, no explanation:
{
  "experience": [
    {
      "title":    "...",
      "company":  "...",
      "location": "...",
      "duration": "...",
      "bullets":  ["ALL bullets reordered, most relevant first"]
    }
  ],
  "projects": [
    {
      "name":    "...",
      "tech":    "...",
      "bullets": ["ALL bullets, most relevant first"]
    }
  ]
}"""


def seed_generic_prompts() -> dict:
    """
    Seeds all generic prompts (same for every user).
    Safe to call multiple times -- never overwrites existing prompts.
    Returns {'created': n, 'skipped': n}.
    """
    created = 0
    skipped = 0

    for name, content, desc in [
        (PROMPT_INTAKE_QUESTIONS, _GENERIC_INTAKE_QUESTIONS,
         "Generates targeted questions from any resume."),
        (PROMPT_INTAKE_XML, _GENERIC_INTAKE_XML,
         "Builds resume_data.xml from resume + Q&A answers."),
        (PROMPT_INTAKE_XML_DIRECT, _GENERIC_INTAKE_XML_DIRECT,
         "Builds resume_data.xml from resume PDF text only (no Q&A)."),
        (PROMPT_EXPERIENCE_ENHANCE, _GENERIC_EXPERIENCE_ENHANCE,
         "Rewrites experience bullets to be punchy and achievement-focused."),
        (PROMPT_JOB_EXPERIENCE_PRIORITY, _GENERIC_JOB_EXPERIENCE_PRIORITY,
         "Reorders and selects experience/project bullets by job relevance."),
    ]:
        if not prompt_exists(name):
            set_prompt(name, content, desc)
            created += 1
        else:
            skipped += 1

    return {"created": created, "skipped": skipped}


# -- Personal prompt generation ------------------------------------
def generate_personal_prompts(profile: dict, api_client,
                               overwrite: bool = False) -> dict:
    """
    Generates personalized prompts from the user's actual profile.
    Called automatically -- users never call this directly.

    Uses Claude to read the real profile and write prompts that
    describe THIS person's specialization, what roles fit them,
    and how to honestly tailor their resume. No hardcoded content.

    api_client : an initialized anthropic.Anthropic() client
    overwrite  : if False, skips prompts that already exist
    Returns {'created': n, 'skipped': n}
    """
    created = 0
    skipped = 0

    # Build a compact profile summary for the prompt generator
    all_skills = []
    for items in (profile.get("skills") or {}).values():
        if isinstance(items, list):
            all_skills.extend(items)

    jobs = [
        {
            "title":    j.get("title", ""),
            "company":  j.get("company", ""),
            "duration": j.get("duration", ""),
        }
        for j in (profile.get("experience") or [])
    ]

    projects = [
        {"name": p.get("name", ""), "tech": p.get("tech", "")}
        for p in (profile.get("projects") or [])
    ]

    education = [
        {"name": d.get("name", ""), "school": d.get("school", "")}
        for d in (profile.get("education") or [])
    ]

    profile_summary = json.dumps({
        "name":      profile.get("name", ""),
        "summary":   profile.get("summary", ""),
        "skills":    all_skills,
        "jobs":      jobs,
        "projects":  projects,
        "education": education,
    }, indent=2)

    # -- Generate relevance_check prompt -------------------------
    if not overwrite and prompt_exists(PROMPT_RELEVANCE_CHECK):
        skipped += 1
    else:
        print("  [AI] Generating your personalized relevance check prompt...")
        response = api_client.messages.create(
            model=AI_MODEL_QUALITY,
            max_tokens=2000,
            system=(
                "You write prompts for AI systems. "
                "Return only the prompt text -- no explanation, "
                "no preamble, no markdown."
            ),
            messages=[{
                "role": "user",
                "content": f"""Here is a software engineer's profile:

{profile_summary}

Write a highly specific job relevance check prompt for this person.
The prompt will be used by an AI career advisor to score every LinkedIn
job posting for this exact candidate.

Requirements:
1. DOMAIN — name their PRIMARY technical domain explicitly (e.g. "enterprise
   .NET/C# backend development for banking/fintech" not just "software engineer")
2. STRONG MATCH roles — list 8-12 specific role titles that ARE a good fit
   based on their actual stack and experience (be very specific)
3. WEAK/NO MATCH roles — list role types they should skip because the required
   specialization is genuinely absent from their background
4. SCORING GUIDANCE — explain how to score:
   - 80-100: their core stack matches the JD closely
   - 60-79: significant overlap, some gaps but transferable
   - 40-59: adjacent domain, meaningful skill transfer possible
   - below 40: too far from their background
5. RULES:
   - Never reject a role purely based on years of experience
   - Generic skills (Python, Git, communication) shared with a specialized role
     do NOT make it a match — domain fit matters most
   - Only flag ineligible if job EXPLICITLY requires US citizenship or active security clearance
   - "No sponsorship" or "must be authorized to work" are NOT blockers for CPT/OPT candidates
   - Report specialization_gap honestly even for internships
   - The candidate profile and full job description will be injected at runtime
6. Be opinionated — a vague prompt produces vague scores. This person needs
   to find jobs where they genuinely have a strong chance.

End the prompt with exactly this JSON instruction block (no changes):

Return ONLY valid JSON, no markdown:
{{
    "is_relevant"        : true or false,
    "match_score"        : 0-100,
    "skill_overlap"      : 0-100,
    "domain_match"       : true or false,
    "transferable"       : true or false,
    "specialization_gap" : true or false,
    "role_equivalent"    : "what this role maps to in the candidate's background",
    "reason"             : "1-2 sentence plain English explanation",
    "matched_skills"     : ["skill1", "skill2"],
    "missing_skills"     : ["skill1", "skill2"]
}}

Write the prompt now. Return only the prompt text, no preamble."""
            }]
        )
        content = response.content[0].text.strip()
        set_prompt(
            PROMPT_RELEVANCE_CHECK,
            content,
            f"Personalized relevance check for {profile.get('name', 'user')}.",
        )
        created += 1
        print("  [OK] Relevance check prompt generated.")

    # -- Generate resume_tailor prompt ----------------------------
    if not overwrite and prompt_exists(PROMPT_RESUME_TAILOR):
        skipped += 1
    else:
        print("  [AI] Generating your personalized resume tailor prompt...")
        response = api_client.messages.create(
            model=AI_MODEL_QUALITY,
            max_tokens=2000,
            system=(
                "You write prompts for AI systems. "
                "Return only the prompt text -- no explanation, "
                "no preamble, no markdown."
            ),
            messages=[{
                "role": "user",
                "content": f"""Here is a software engineer's profile:

{profile_summary}

Write a resume tailoring prompt for this specific person. The prompt will
be used by an AI to tailor their resume for a specific job -- re-emphasizing
real experience without fabricating anything.

The prompt must:
1. State clearly that the AI may ONLY use skills, technologies, domains, and
   experience that actually appear in this person's profile.
2. List specific things from this person's background that are real and can
   be emphasized.
3. Describe what is NOT in their background -- things that must never be
   invented or implied.
4. Include these tailoring rules:
   - SUMMARY: rewrite to foreground what is genuinely relevant. Keep real
     years of experience. Every noun must be something they have actually done.
   - SKILLS: re-order real skills so the most job-relevant appear first.
     Never add a skill they do not have.
   - EXPERIENCE: copy every bullet EXACTLY word for word. Never change anything.
   - PROJECTS: select projects whose real tech best matches the job. Re-phrase
     bullets to foreground relevant real details, but never add things that
     are not there. Return 2-4 bullets per project.
5. Say that candidate profile and job description will be injected at runtime.
6. End with this exact JSON format instruction:

Return ONLY valid JSON, no markdown:
{{
    "summary": "...",
    "skills_grouped": {{
        "Languages":      ["..."],
        "Frameworks":     ["..."],
        "Tools & DevOps": ["..."],
        "Practices":      ["..."]
    }},
    "experience": [
        {{"title": "...", "company": "...", "location": "...",
          "duration": "...", "bullets": ["..."]}}
    ],
    "projects": [
        {{"name": "...", "tech": "...", "bullets": ["...", "..."]}}
    ],
    "ats_keywords_used": ["..."]
}}

Write the prompt now. Return only the prompt text."""
            }]
        )
        content = response.content[0].text.strip()
        set_prompt(
            PROMPT_RESUME_TAILOR,
            content,
            f"Personalized resume tailor for {profile.get('name', 'user')}.",
        )
        created += 1
        print("  [OK] Resume tailor prompt generated.")

    # Store the profile hash so we can detect when it changes
    if created > 0 and profile:
        from api.prompts import get_profile_hash, store_profile_hash
        store_profile_hash(get_profile_hash(profile))
        print("  [OK] Profile signature stored.")

    return {"created": created, "skipped": skipped}


def setup_all_prompts(profile: dict, api_client,
                      overwrite: bool = False) -> dict:
    """
    One call that does everything:
      1. Seeds the generic prompts (intake_questions, intake_xml_builder)
      2. Generates the personal prompts (relevance_check, resume_tailor)

    This is the only function resume_intake.py and migrate_prompts.py
    need to call. Users never call this directly.

    Returns total {'created': n, 'skipped': n}.
    """
    g = seed_generic_prompts()
    p = generate_personal_prompts(profile, api_client, overwrite=overwrite)
    return {
        "created": g["created"] + p["created"],
        "skipped": g["skipped"] + p["skipped"],
    }